theme                  : "minimal-mistakes-jekyll"
# remote_theme           : "mmistakes/minimal-mistakes"
# remote_theme: academicpages/academicpages.github.io
# show_downloads: true
# github: [metadata]

# Basic Site Settings
locale                   : "en-GB"
title                    : "Sara Sousi"
title_separator          : "-"
name                     : &name "Sara Sousi"
description              : &description "personal description"
url                      : https://sarasousi.github.io 
repository               : "SaraSousi/SaraSousi.github.io"


author:
  # Biographic information
  name             : "Sara Sousi"
  avatar           : "https://avatars.githubusercontent.com/u/63481742?v=4"
  bio              : "Data Scientist & Researcher"
  location         : "London, UK"
  employer         : "EY, UCL"
  email            : "sara.sousi@icloud.com" 
  # Websites
  github           : "SaraSousi"
  linkedin         : "sara-sousi"
  # Academic websites
  googlescholar    : "https://scholar.google.com/citations?user=P64jnJ8AAAAJ&hl=en"
  orcid            : "https://orcid.org/my-orcid?orcid=0000-0002-0494-5138"
  pubmed           : "https://pubmed.ncbi.nlm.nih.gov/?term=Sara+Sousi&sort=date"
  researchgate     : "https://www.researchgate.net/profile/Sara_Sousi"

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# Publication Category - The following the list of publication categories and their headings
publication_category:
  manuscripts:
    title: 'Journal Articles'    
  conferences:
    title: 'Conference Papers'

# SEO Related
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :

# Analytics
analytics:
  provider               :  "false" # false (default), "google", "google-universal", "google-analytics-4", "custom"
  google:
    tracking_id          :
    
# These settings control the types of collections used by the template
collections:
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/

# These settings control how pages and collections are included in the site
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _publications
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true
      comment: true
