#theme: jekyll-theme-minimal
remote_theme: "mmistakes/minimal-mistakes"
show_downloads: true
github: [metadata]

# Basic Site Settings
locale                   : "en-GB"
title                    : Sara Sousi
title_separator          : "-"
name                     : &name "Sara Sousi"
#url                      : "https://sarasousi.github.io"
repository               : "SaraSousi/SaraSousi.github.io"
